(window.webpackJsonp=window.webpackJsonp||[]).push([["BottomNavigation"],{"./manifest/temp/material/BottomNavigation.js":function(e,t,o){"use strict";t.__esModule=!0;var a=function(e){return e&&e.__esModule?e:{default:e}}(o("./node_modules/@material-ui/core/BottomNavigation/index.js"));t.BottomNavigation=a.default},"./node_modules/@material-ui/core/BottomNavigation/BottomNavigation.js":function(e,t,o){"use strict";var a=o("./node_modules/@babel/runtime/helpers/builtin/interopRequireDefault.js");Object.defineProperty(t,"__esModule",{value:!0}),t.default=t.styles=void 0;var n=a(o("./node_modules/@babel/runtime/helpers/builtin/extends.js")),s=a(o("./node_modules/@babel/runtime/helpers/builtin/objectWithoutProperties.js")),l=a(o("react")),i=(a(o("./node_modules/prop-types/index.js")),a(o("./node_modules/classnames/index.js"))),r=a(o("./node_modules/@material-ui/core/styles/withStyles.js")),u=function(e){return{root:{display:"flex",justifyContent:"center",height:56,backgroundColor:e.palette.background.paper}}};function d(e){var t=e.children,o=e.classes,a=e.className,r=e.onChange,u=e.showLabels,d=e.value,p=(0,s.default)(e,["children","classes","className","onChange","showLabels","value"]),m=(0,i.default)(o.root,a),c=l.default.Children.map(t,function(e,t){if(!l.default.isValidElement(e))return null;var o=void 0===e.props.value?t:e.props.value;return l.default.cloneElement(e,{selected:o===d,showLabel:void 0!==e.props.showLabel?e.props.showLabel:u,value:o,onChange:r})});return l.default.createElement("div",(0,n.default)({className:m},p),c)}t.styles=u,d.propTypes={},d.defaultProps={showLabels:!1};var p=(0,r.default)(u,{name:"MuiBottomNavigation"})(d);t.default=p},"./node_modules/@material-ui/core/BottomNavigation/index.js":function(e,t,o){"use strict";var a=o("./node_modules/@babel/runtime/helpers/builtin/interopRequireDefault.js");Object.defineProperty(t,"__esModule",{value:!0}),Object.defineProperty(t,"default",{enumerable:!0,get:function(){return n.default}});var n=a(o("./node_modules/@material-ui/core/BottomNavigation/BottomNavigation.js"))},"./node_modules/classnames/index.js":function(e,t,o){var a;
/*!
  Copyright (c) 2017 Jed Watson.
  Licensed under the MIT License (MIT), see
  http://jedwatson.github.io/classnames
*/
/*!
  Copyright (c) 2017 Jed Watson.
  Licensed under the MIT License (MIT), see
  http://jedwatson.github.io/classnames
*/
!function(){"use strict";var o={}.hasOwnProperty;function n(){for(var e=[],t=0;t<arguments.length;t++){var a=arguments[t];if(a){var s=typeof a;if("string"===s||"number"===s)e.push(a);else if(Array.isArray(a)&&a.length){var l=n.apply(null,a);l&&e.push(l)}else if("object"===s)for(var i in a)o.call(a,i)&&a[i]&&e.push(i)}}return e.join(" ")}void 0!==e&&e.exports?(n.default=n,e.exports=n):void 0===(a=function(){return n}.apply(t,[]))||(e.exports=a)}()}}]);