(window.webpackJsonp=window.webpackJsonp||[]).push([["Paper"],{"./manifest/temp/material/Paper.js":function(e,r,t){"use strict";r.__esModule=!0;var o=function(e){return e&&e.__esModule?e:{default:e}}(t("./node_modules/@material-ui/core/Paper/index.js"));r.Paper=o.default},"./node_modules/@material-ui/core/Paper/Paper.js":function(e,r,t){"use strict";var o=t("./node_modules/@babel/runtime/helpers/builtin/interopRequireDefault.js");Object.defineProperty(r,"__esModule",{value:!0}),r.default=r.styles=void 0;var a=o(t("./node_modules/@babel/runtime/helpers/builtin/extends.js")),n=o(t("./node_modules/@babel/runtime/helpers/builtin/defineProperty.js")),s=o(t("./node_modules/@babel/runtime/helpers/builtin/objectWithoutProperties.js")),u=o(t("./node_modules/@babel/runtime/helpers/builtin/objectSpread.js")),l=o(t("react")),i=(o(t("./node_modules/prop-types/index.js")),o(t("./node_modules/classnames/index.js"))),d=(o(t("./node_modules/@material-ui/core/node_modules/warning/warning.js")),o(t("./node_modules/@material-ui/core/styles/withStyles.js"))),p=function(e){var r={};return e.shadows.forEach(function(e,t){r["elevation".concat(t)]={boxShadow:e}}),(0,u.default)({root:{backgroundColor:e.palette.background.paper},rounded:{borderRadius:2}},r)};function c(e){var r=e.classes,t=e.className,o=e.component,u=e.square,d=e.elevation,p=(0,s.default)(e,["classes","className","component","square","elevation"]),c=(0,i.default)(r.root,r["elevation".concat(d)],(0,n.default)({},r.rounded,!u),t);return l.default.createElement(o,(0,a.default)({className:c},p))}r.styles=p,c.propTypes={},c.defaultProps={component:"div",elevation:2,square:!1};var m=(0,d.default)(p,{name:"MuiPaper"})(c);r.default=m},"./node_modules/@material-ui/core/Paper/index.js":function(e,r,t){"use strict";var o=t("./node_modules/@babel/runtime/helpers/builtin/interopRequireDefault.js");Object.defineProperty(r,"__esModule",{value:!0}),Object.defineProperty(r,"default",{enumerable:!0,get:function(){return a.default}});var a=o(t("./node_modules/@material-ui/core/Paper/Paper.js"))},"./node_modules/classnames/index.js":function(e,r,t){var o;
/*!
  Copyright (c) 2017 Jed Watson.
  Licensed under the MIT License (MIT), see
  http://jedwatson.github.io/classnames
*/
/*!
  Copyright (c) 2017 Jed Watson.
  Licensed under the MIT License (MIT), see
  http://jedwatson.github.io/classnames
*/
!function(){"use strict";var t={}.hasOwnProperty;function a(){for(var e=[],r=0;r<arguments.length;r++){var o=arguments[r];if(o){var n=typeof o;if("string"===n||"number"===n)e.push(o);else if(Array.isArray(o)&&o.length){var s=a.apply(null,o);s&&e.push(s)}else if("object"===n)for(var u in o)t.call(o,u)&&o[u]&&e.push(u)}}return e.join(" ")}void 0!==e&&e.exports?(a.default=a,e.exports=a):void 0===(o=function(){return a}.apply(r,[]))||(e.exports=o)}()}}]);